#!/bin/bash
#
# acc_hist
#
# created: 26.09.2013
# by zinke
#

Usage() {
cat << EOF

    Usage: $0 <> [options]

WORK IN PROGRES!

    OPTIONS:
            -

            ###########################################################
            ##   (c) wolf zinke (2013) - part of the MaFIA toolbox   ##
            ##         > MAcaque Functional Image Analysis <         ##
            ##            Licensed under the MIT license             ##
            ###########################################################


EOF
exit 1

}


if [ $# -lt 1 ]; then
    Usage
else
    arg1=$1;
    shift
fi

#__________________________________________________________________________________________#

while [ $# -gt 0 ] ;
do
    case $1 in
           -)
                shift
                ;;
          -*)   echo "Wrong option: <$1>"
                echo ""
                Usage
                ;;
           *)   break
                ;;
    esac
done

#__________________________________________________________________________________________#

srcpath=`dirname $(which $0)`

echo "source('$srcpath/AccHist.r'); AccHist('${cdir}RvsL_brainacc.dat','$onm'); q();" | R --vanilla --slave
