#!/bin/bash
#
# ArtIP
#
# created: 29.01.2013
# by wolf
#

Usage() {
cat << EOF

    Usage: $0 <infl> artvol -o

        Submitts all <fsfdir> files found in directory to condor. This argument
        also could refer to a text file listing all fsf files.

    OPTIONS:
            -o      name of the corrected file
            -mem    expected memory usage (default: 8GB)
            -idir   initial directory (default: pwd)
            -loc    run locally instead of using condor
            -lp     number of local processors used. This sets
                    also the -loc argument. (requires condor_waitend!)
            -sub    submit the files
            -msg    get mail notification when job finishes

            ###########################################################
            ##   (c) wolf zinke (2017) - part of the MaFIA toolbox   ##
            ##         > MAcaque Functional Image Analysis <         ##
            ##            Licensed under the MIT license             ##
            ###########################################################


EOF
exit 1

}

if [ $# -lt 1 ]; then
    Usage
else
    fsfdir=$1;
    shift
fi

