#!/bin/bash
#
# brainwave
#
# created: 27.04.2014
# by zinke
#

Usage() {
cat << EOF

    Usage: $0 <Infile> [options]

    Wrapper script that uses the BrainWavelet toolbox for data denoising
    [http://www.brainwavelet.org]

    Patel AX, Kundu P, Rubinov M, Jones PS, Vertes PE, Ersche KD, Suckling J, Bullmore ET.
    A wavelet method for modeling and despiking motion artifacts from resting-state fMRI time series.
    NeuroImage (2014). http://dx.doi.org/10.1016/j.neuroimage.2014.03.012

    OPTIONS:
            -o    output file name stem
            -wv   wavelet to use (default: d4)
            -thr  Threshold for maximal and minimal wavelet coefficients (default=10).
            -bnd  Boundary condition to apply: 'circular' or 'reflection' (default).
            -ram  Specify RAM usage in GB

            ###########################################################
            ##   (c) wolf zinke (2014) - part of the MaFIA toolbox   ##
            ##         > MAcaque Functional Image Analysis <         ##
            ##            Licensed under the MIT license             ##
            ###########################################################


EOF
exit 1

}


if [ $# -lt 1 ]; then
    Usage
else
    flin=$1;
    shift
fi

P2BW="/DATA/BrainWavelet" # root path to the brainwavelet toolbox

#__________________________________________________________________________________________#

ofl="$(remove_ext $flin)_dn"
wv="d4"
thr=10
bnd="reflection"
ram=""

while [ $# -gt 0 ] ;
do
    case $1 in
          -o)   ofl=$2
                shift 2
                ;;
         -wv)   wv=$2
                shift 2
                ;;
        -thr)   thr=$2
                shift 2
                ;;
        -bnd)   bnd=$2
                shift 2
                ;;
        -ram)   ram=", 'LimitRAM', $2"
                shift 2
                ;;
          -*)   echo "Wrong option: <$1>"
                echo ""
                Usage
                ;;
           *)   break
                ;;
    esac
done

#__________________________________________________________________________________________#


echo "path('$P2BW/BWT',path);
path('$P2BW/third_party/cprintf',path);
path('$P2BW/third_party/NIfTI',path);
path('$P2BW/third_party/wmtsa/dwt',path);
path('$P2BW/third_party/wmtsa/utils',path);

WaveletDespike('$flin','$ofl', 'wavelet','$wv', 'threshold',$thr, 'boundary','$bnd', 'compress',1 $ram);
exit" | matlab -nojvm -nodisplay -nosplash -nodesktop

