#!/bin/bash
#
# condor_addcmd
#
# created: 08.08.2013
# by zinke
#

Usage() {
cat << EOF

    Usage: $0 <argstr> [options]

        adds a command block to a condor submit file

    OPTIONS:
            -o      name of submit file (not working yet, use >> instead)
            -log    name stem of error and output files (process number will be appended)
            -shim   add extra entries required if shim_dmctp is used


            ###########################################################
            ##   (c) wolf zinke (2013) - part of the MaFIA toolbox   ##
            ##         > MAcaque Functional Image Analysis <         ##
            ##            Licensed under the MIT license             ##
            ###########################################################


EOF
exit 1

}

if [ $# -lt 1 ]; then
    Usage
else
    argstr=$1;
    shift
fi

#__________________________________________________________________________________________#
ostr=""
keeplog=0
do_shim=0

while [ $# -gt 0 ] ;
do
    case $1 in
          -o)   ostr=">> $2"
                shift 2
                ;;
        -log)   keeplog=1
                lognm=$2
                mkdir -p $(dirname ${lognm})
                shift 2
                ;;
       -shim)   do_shim=1
                shift
                ;;
          -*)   echo "Wrong option: <$1>"
                echo ""
                Usage
                ;;
           *)   break
                ;;
    esac
done

#__________________________________________________________________________________________#

if [ $do_shim -eq 0 ]
then
    echo "arguments = \"$argstr \""  $ostr
    if [ $keeplog -eq 1 ]
    then
        echo "error  = ${lognm}_\$(Process).e"   $ostr
        echo "output = ${lognm}_\$(Process).o"   $ostr
    fi
    echo "Queue" $ostr
    echo ""      $ostr
else
    echo "arguments = \"\$(dmtcp_args) $argstr\"" $ostr
    echo "environment = \$(dmtcp_env)" $ostr

    echo "Queue" $ostr
    echo "" $ostr
fi
