#!/bin/bash
#
# cropimg
#
# created: 29.01.2010
# by wolf
#

Usage() {
cat << EOF

    Usage: $0 <flnm> [options]

        reduce image size to comprise only voxels with signal,
        but keep the voxel origin

    OPTIONS:
            -o      output name

            ###########################################################
            ##   (c) wolf zinke (2010) - part of the MaFIA toolbox   ##
            ##         > MAcaque Functional Image Analysis <         ##
            ##     for comments and questions: wolfzinke@gmx.net     ##
            ###########################################################


EOF
exit 1

}

if [ $# -lt 1 ]; then
    Usage
else
    flnm=$(remove_ext $1)
    shift
fi

#__________________________________________________________________________________________#


outfile=${flnm}_crop

while [ $# -gt 0 ] ;
do
    case $1 in
          -o)   outfile=$2
                shift 2
                ;;
          -*)   echo "Wrong option: <$1>"
                echo ""
                Usage
                ;;
           *)   break
                ;;
    esac
done

#__________________________________________________________________________________________#

fslmaths ${flnm} -abs -bin  /tmp/tmp_roiext -odt char

roi=$(fslstats /tmp/tmp_roiext -w) #vector defining cube comprising voxels with signal
rm /tmp/tmp_roiext*

xr=$(echo $roi | cut -d\  -f1,2)
yr=$(echo $roi | cut -d\  -f3,4)
zr=$(echo $roi | cut -d\  -f5,6)

fslroi ${flnm}  $xr  $yr  $zr  $outfile
