#!/bin/bash
#
# mk_sphere
#
# by zinke
#


Usage() {
cat << EOF

    Usage: $0 <ref> <coor> <radius>  <ooutname>

        create a spherical ROI with given radius centered at the voxel

EOF
exit 1

}

if [ $# -lt 6 ]
then
    Usage
else
    ref=$1
    X=$2
    Y=$3
    Z=$4
    radius=$5
    onm=$6
fi

#tmpnm=$(tmpnam tmpSphere)

fslmaths ${ref} -mul 0 -add 1 -bin -roi $X 1 $Y 1 $Z 1 0 1  -kernel sphere $radius -fmean -thr .00001 -bin ${onm} -odt char

#rm  ${tmpnm}_vxl*
