#!/bin/bash
#
# nifti2Blender
#
# created: 11.09.2014
# by zinke
#

Usage() {
cat << EOF

    Usage: $0 <infl> [options]

    Based on: http://spm.martinpyka.de/?p=127


    OPTIONS:
            -o      output name
            -s      scaling factor
            ip      image interpolation

            ###########################################################
            ##   (c) wolf zinke (2014) - part of the MaFIA toolbox   ##
            ##         > MAcaque Functional Image Analysis <         ##
            ##            Licensed under the MIT license             ##
            ###########################################################


EOF
exit 1

}


if [ $# -lt 1 ]; then
    Usage
else
    arg1=$1;
    shift
fi

#__________________________________________________________________________________________#

while [ $# -gt 0 ] ;
do
    case $1 in
           -)
                shift
                ;;
          -*)   echo "Wrong option: <$1>"
                echo ""
                Usage
                ;;
           *)   break
                ;;
    esac
done

#__________________________________________________________________________________________#


# path to FSL matlab tools
FSLmat="$FSLDIRetc/matlab"

        fslmat = fullfile(fslpth(1:end-1), 'etc/matlab');
        if(~exist(fslmat,'dir'))
            error('FSL ist not correctly installed on the system!')
        else
            addpath(fslmat);
        end

ZMAP = read_avw(statmap);



addpath(fslmat);
vol = spm_vol(img);
data = spm_read_vols(vol);
data = uint8(data*scaling);
figure, imagesc(data(:,:,50))
fid = fopen(output, 'wb')
fwrite(fid, data, 'uint8')
fclose(fid)