#!/bin/bash
#
# nii2png
#
# created: 07.01.2010
# by zinke
#

lst=`ls -1 *.nii*`

if hash parallel 2>/dev/null
then
    parallel  CompReg ::: $lst
else
    for cfl in $lst
    do
        if [ `fslnvols $cfl` -eq 1 ]
        then
            CompReg $cfl
        fi
    done
fi
