#!/bin/bash
#
# octcalc
#
# created: 25.05.2013
# by zinke
#

Usage() {
cat << EOF

    Usage: $0 <"expression">

           evaluates the expression by piping it to octave (octave/matlab syntax applies)

            ###########################################################
            ##   (c) wolf zinke (2013) - part of the MaFIA toolbox   ##
            ##         > MAcaque Functional Image Analysis <         ##
            ##   for comments and questions: wolfzinke@gmail.com     ##
            ##            Licensed under the MIT license             ##
            ###########################################################


EOF
exit 1

}

if [ $# -lt 1 ]; then
    Usage
else
    funcal=$1
fi
 
#__________________________________________________________________________________________#

echo "RES=$funcal; disp(RES);" | octave --silent --no-window-system -f -H
#__________________________________________________________________________________________#
 
