#!/bin/bash
#

Usage() {
cat << EOF

    Usage: set_origin <filename> <Xctr> <Yctr> <Zctr> [options]

           Sets given voxel position as zero.

    OPTIONS:
            -o  alternative name for output

            ###########################################################
            ##   (c) wolf zinke (2008) - part of the MaFIA toolbox   ##
            ##       for comments and questions: wolfzinke@gmx.net   ##
            ###########################################################

EOF
    exit 1
}

#----------------------------------------------------------------------#
if [ $# -lt 4 ]
then
    Usage
else
    infl=`remove_ext $1`
    Xctr=$2
    Yctr=$3
    Zctr=$4

    shift 4
fi

if [ `imtest $infl` -eq  0 ]
then
    echo "ERROR: File <$infl> does not exist!"
    exit
fi

#----------------------------------------------------------------------#
outnm=$infl
chngfl=1

# get options
while [ $# -gt 0 ] ;
do
    case $1 in
      -o)   outnm=$2
            chngfl=0
            shift 2
            ;;
      -*)   echo "Wrong option: <$1>"
            echo ""
            Usage
            ;;
       *)   break
            ;;
    esac
done

#----------------------------------------------------------------------#
# hdinfo=`fslinfo $infl`

xsize=`   fslval $infl dim1`
ysize=`   fslval $infl dim2`
zsize=`   fslval $infl dim3`
tsize=`   fslval $infl dim4`
xvoxsize=`fslval $infl pixdim1`
yvoxsize=`fslval $infl pixdim2`
zvoxsize=`fslval $infl pixdim3`
TR=`      fslval $infl pixdim4`
datatype=`fslval $infl datatype`

#----------------------------------------------------------------------#
xorigin=$Xctr
yorigin=$Yctr
zorigin=$Zctr

#----------------------------------------------------------------------#
if [ $chngfl -eq 0 ]
then
    imcp $infl $outnm
fi

fslcreatehd $xsize $ysize $zsize $tsize $xvoxsize $yvoxsize $zvoxsize $TR $xorigin $yorigin $zorigin $datatype $outnm


