#!/bin/bash
#
# function requires ccalc provided by the AFNI package
#

if [ $# -lt 1 ] ; then
    echo ''
    echo 'Usage: sigma2fwhm <sigma>'
    echo '       calculates the FWHM of a gaussian kernel for a given sigma'
    echo '       '

    exit
else
#   str=`echo "ccalc -eval '$1 * sqrt(8*log(2))'"`
#   eval "$str"

  #octcalc "$1 * sqrt(8*log(2))"
  Rscript -e "round($1 * sqrt(8*log(2)),4)"  --vanilla | cut -d] -f2

fi

