#!/bin/bash
#
# vol_MCC
#
# created: 06.09.2015
# by zinke
#

Usage() {
cat << EOF

    Usage: $0 <> [options]

    OPTIONS:
            -o      output file name
            -t      type of correctiont: "holm" (default), "hochberg",
                    "hommel", "bonferroni", "BH", "BY", "fdr"
            -m      mask image to constrain relevant voxel

    This tool requires R the the package 'oro.nifti'.


            ###########################################################
            ##   (c) wolf zinke (2015) - part of the MaFIA toolbox   ##
            ##         > MAcaque Functional Image Analysis <         ##
            ##            Licensed under the MIT license             ##
            ###########################################################


EOF
exit 1

}


if [ $# -lt 1 ]; then
    Usage
else
    flin=$1;
    shift
fi


srcpath=`dirname $(which $0)`

#__________________________________________________________________________________________#

ofl="$(remove_ext $flin)_mcc.nii.gz"
argstr=""

while [ $# -gt 0 ] ;
do
    case $1 in
          -o)   ofl=$2
                shift 2
                ;;
          -t)   argstr="$argstr, method='$2'"
                shift 2
                ;;
          -m)   argstr="$argstr, mask='$2'"
                shift 2
                ;;
          -*)   echo "Wrong option: <$1>"
                echo ""
                Usage
                ;;
           *)   break
                ;;
    esac
done

#__________________________________________________________________________________________#


echo "source('$srcpath/vol_MCC.r'); vol_MCC('$flin', ofl='$ofl' $argstr ); q();" | R --vanilla --slave


